Fix test cases for non C.UTF-8 locale
If the locale is not set to `C.UTF-8` two test cases can fail:

```
$ LC_ALL=de_DE.UTF-8 APPORT_TEST_NOXVFB=1 test/run problem_report ui
======================================================================
ERROR: test_basic_operations (__main__.T)
basic creation and operation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_problem_report.py", line 35, in test_basic_operations
    self.assertTrue(time.strptime(pr['Date']))
  File "/usr/lib/python3.10/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Wed Apr 20 19:12:25 2022' does not match format '%a %b %d %H:%M:%S %Y'

======================================================================
FAIL: test_format_filesize (__main__.T)
format_filesize()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_ui.py", line 214, in test_format_filesize
    self.assertEqual(self.ui.format_filesize(0), '0.0 KB')
AssertionError: '0,0 KB' != '0.0 KB'
- 0,0 KB
?  ^
+ 0.0 KB
?  ^

----------------------------------------------------------------------
```

Set the locale for those two tests to `C.UTF-8` because they expect US
English formatting.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>