Fix mypy for 'suppress' in apport/ui.py
mypy complains:

```
apport/ui.py:971: error: Incompatible types in assignment (expression has type "bool", variable has type "Union[_SUPPRESS_T, str]")
```

The `help` parameter for `add_argument` takes `Optional[Text]`.
Therefore set `suppress` to `None` if the help should not be suppressed.

Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>