Replace ProblemReport.get_date by .get_timestamp
Apport 2.21.0-0ubuntu2 fails:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport/report.py", line 205, in _run_hook
    symb['add_info'](report, ui)
  File "/usr/share/apport/general-hooks/generic.py", line 94, in add_info
    apport.hookutils.attach_journal_errors(report)
  File "/usr/lib/python3/dist-packages/apport/hookutils.py", line 740, in attach_journal_errors
    crash_time = report.get_date()
  File "/usr/lib/python3/dist-packages/problem_report.py", line 268, in get_date
    return datetime.datetime.strptime(self['Date'], '%a %b %d %H:%M:%S %Y')
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Sun Jun 12 19:52:55 2022' does not match format '%a %b %d %H:%M:%S %Y'
```

`Report.get_timestamp` does the same than `ProblemReport.get_date`
except it handles the locale correctly and returns a timestamp instead
of a datetime object. So move `get_timestamp` from `Report` to the
parent class `ProblemReport` and replace the single usage of
`ProblemReport.get_date` by `ProblemReport.get_timestamp`. Let
`ProblemReport.get_timestamp` return an `int` instead of `float` since
the report date granularity is seconds. Also ensure that
`ProblemReport.get_timestamp` is used in all possible cases.

Bug: https://launchpad.net/bugs/1978487
Fixes: a32fb956c145 ("Grab a slice of JournalErrors around the crash time")
Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>