test: Use MagicMock for subprocess.CompletedProcess.args
mypy complains:

```
error: Argument "args" to "CompletedProcess" has incompatible type "None"; expected "str | bytes | PathLike[str] | PathLike[bytes] | Sequence[str | bytes | PathLike[str] | PathLike[bytes]]"  [arg-type]
```

Since `subprocess.CompletedProcess.args` is not used by the tests use
`MagicMock` to make mypy happy.

Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>