general-hooks/generic.py: Fix FileNotFoundError if home does not exist
Running the test suite during the Debian package build will show a lot
of `FileNotFoundError`, because sbuild sets the home directory to a
non-existing path:

```
ERROR: hook ./data/general-hooks/generic.py crashed:
Traceback (most recent call last):
  File "apport/report.py", line 205, in _run_hook
    symb['add_info'](report, ui)
  File "./data/general-hooks/generic.py", line 34, in add_info
    st = os.statvfs(mount)
FileNotFoundError: [Errno 2] No such file or directory: '/sbuild-nonexistent'
```

Skip the free memory check if the home directory does not exist.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>