tests: Use shadow in *_different_binary_source
The kernel binary package is usually not installed in container
environments (like schroot or docker). Then the three
`*_update_report_different_binary_source` test cases will fail:

```
ERROR: test_run_update_report_different_binary_source (tests.test_ui.T)
run_update_report() on a source package which does not have a binary of the same name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 281, in __getitem__
    rawpkg = self._cache[key]
KeyError: 'linux-image-5.15.0-30-generic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apport/packaging_impl.py", line 148, in _apt_pkg
    return self._cache()[package]
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 283, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'linux-image-5.15.0-30-generic'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/test_ui.py", line 1756, in test_run_update_report_different_binary_source
    kernel_src = apport.packaging.get_source(kernel_pkg)
  File "apport/packaging_impl.py", line 181, in get_source
    if self._apt_pkg(package).installed:
  File "apport/packaging_impl.py", line 150, in _apt_pkg
    raise ValueError('package %s does not exist' % package)
ValueError: package linux-image-5.15.0-30-generic does not exist
```

The three `*_update_report_different_binary_source` test cases only
require a source package name that is not an installed binary package.
Use `shadow` instead of the kernel source package name, since it has
priority `required` and it produces the essential binary package
`login`.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>