apport_python_hook: Try to create report directory if missing
Found stack trace in failing autopkgtest of ubuntu-release-upgrader:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 142, in apport_excepthook
    os.open(pr_filename, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640),
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_nosetests3.1000.crash'
```

This kind of stack trace happens if the report directory does not exist.

Try to create the report directory if it is missing. If that fails, do
not write the crash report.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>