Drop unneeded Errno 13 check from _address_to_offset
```
$ test/run report

======================================================================
ERROR: test_address_to_offset (__main__.T)
_address_to_offset()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_report.py", line 2175, in test_address_to_offset
    self.assertRaises(AssertionError, pr._address_to_offset, 0)
  File "/usr/lib/python3.10/unittest/case.py", line 738, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.10/unittest/case.py", line 201, in handle
    callable_obj(*args, **kwargs)
  File "apport/report.py", line 1757, in _address_to_offset
    if 'Errno 13' in self['ProcMaps']:
  File "/usr/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: 'ProcMaps'

----------------------------------------------------------------------
```

`Report._address_to_offset` is a private method that is only called by
`Report.crash_signature_addresses` which already checks if `Errno 13` is
in ProcMaps. So just drop this check from `Report._address_to_offset`.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>