test: fix expected traceback for Python 3.13
Python 3.13 changes the format of the tracebacks. `test_getcwd_error`
will cause this traceback:

```
Traceback (most recent call last):
  File "/var/tmp/./tmpom46qzi6", line 14, in <module>
    os.getcwd()
    ~~~~~~~~~^^
FileNotFoundError: [Errno 2] No such file or directory
```

So check for `os.getcwd()` and `FileNotFoundError` in the traceback
separately.