test: delete variable instead of setting to None
mypy complains:

```
tests/integration/test_python_crashes.py:408: error: Incompatible types in assignment (expression has type "None", variable has type "Report")  [assignment]
```