tests: Fix GTK UI tests if whoopsie.path is disabled
If the `whoopsie.path` systemd unit is disabled,
`apport.fileutils.allowed_to_report()` will return `False`. Following
GTK UI test cases will fail then:

```
$ tests/run ui_gtk
======================================================================
ERROR: test_crash_noaccept (__main__.T)
Crash report with non-accepting crash DB
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "tests/test_ui_gtk.py", line 759, in test_crash_noaccept
    self.assertTrue(r['Package'].startswith('bash '))
  File "/usr/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: 'Package'

======================================================================
FAIL: test_broken_crash_details (__main__.T)
Broken crash report with showing details
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "tests/test_ui_gtk.py", line 722, in test_broken_crash_details
    self.assertNotEqual(self.error_title, None)
AssertionError: None == None

======================================================================
FAIL: test_crash_details (__main__.T)
Crash report with showing details
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "tests/test_ui_gtk.py", line 647, in test_crash_details
    self.assertEqual(self.app.crashdb.latest_id(), 0)
AssertionError: -1 != 0

======================================================================
FAIL: test_crash_nodetails (__main__.T)
Crash report without showing details
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "tests/test_ui_gtk.py", line 593, in test_crash_nodetails
    self.assertEqual(self.app.crashdb.latest_id(), 0)
AssertionError: -1 != 0

======================================================================
FAIL: test_kerneloops_nodetails (__main__.T)
Kernel oops report without showing details
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "tests/test_ui_gtk.py", line 782, in test_kerneloops_nodetails
    self.assertEqual(self.app.crashdb.latest_id(), 0)
AssertionError: -1 != 0

----------------------------------------------------------------------
```

Mock the calls to `apport.fileutils.allowed_to_report()` because the
test cases expect this function to return `True`.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>