fix: Catch UnicodeDecodeError on a malformed problem report
apport-unpack will crash when passing a binary file that is not valid
UTF-8:

```
$ apport-unpack /bin/ls unpack
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/problem_report.py", line 175, in load
    (key, value) = line.split(b":", 1)
    ^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/apport-unpack", line 91, in <module>
    main()
  File "/usr/bin/apport-unpack", line 67, in main
    pr = load_report(args.report)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/apport-unpack", line 47, in load_report
    pr.load(f, binary=False)
  File "/usr/lib/python3/dist-packages/problem_report.py", line 178, in load
    f"Malformed problem report: Line {line.decode()!r}"
                                      ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 24: invalid start byte
```

When wrapping the `ValueError` into an `MalformedProblemReport`, do not
expect the causing line to be valid UTF-8. Replace the invalid
characters with backslashed escape sequences.

Bug: https://launchpad.net/bugs/1996040
Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>