Fix _run_hook getting called with ui=None
When totem crashes, `source_totem.py` will fail similar to the added
test case `test_hooks_choices_db_no_accept`:

```
ERROR: hook /tmp/tmpu6hm2b3x/package-hooks/coreutils.py crashed:
Traceback (most recent call last):
  File "apport/report.py", line 246, in _run_hook
    symb["add_info"](report, ui)
  File "/tmp/tmpu6hm2b3x/package-hooks/coreutils.py", line 3, in add_info
    answer = ui.choice('YourChoice?', ['foo', 'bar'])
AttributeError: 'NoneType' object has no attribute 'choice'
```

Steps to reproduce with totem:

```
totem &
killall -11 totem
ubuntu-bug /var/crash/_usr_bin_totem.1000.crash
```

In case the database does not accept reports, pass a HookUI instance to
`thread_collect_info` that behaves like a user that cancels all dialogs.

Bug: https://launchpad.net/bugs/1983481
Fixes: f9214a85213d ("only setup a hookui if the crashdb will accept the report[...]")
Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>