test: fix integration tests for coreutils >= 9.4-3ubuntu1
coreutils 9.4-3ubuntu1 in Ubuntu 24.04 (noble) moves files to /usr. This
causes `TestApportValgrind.test_sandbox_cache_options` to fail:

```
ERROR: Cannot find package which ships ExecutablePath /bin/true
```

Use `/usr/bin/true` for `test_sandbox_cache_options` since that is the
new location. Apport already will fall back to look for `/bin/true` in
case `/usr/bin/true` cannot be found.

Bug-Ubuntu: https://launchpad.net/bugs/2054902
Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>