fix: Catch FileNotFoundError for missing desktop files
Desktop files shipped by Debian packages can be removed, which lets
Apport crash:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "tests/unit/test_fileutils.py", line 18, in test_find_package_desktopfile_deleted
    apport.fileutils.find_package_desktopfile("blueman"), None
  File "apport/fileutils.py", line 113, in find_package_desktopfile
    with open(line, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/applications/non-existing/blueman.desktop'
```

Bug: https://launchpad.net/bugs/1997753
Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>