unkillable_shutdown: Fix failure if report file exists
`unkillable_shutdown` will fail if mutliple processes with the same
executable path are still running:

```
======================================================================
FAIL: test_write_reports (tests.integration.test_unkillable_shutdown.TestUnkillableShutdown)
unkillable_shutdown will write reports.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/integration/test_unkillable_shutdown.py", line 114, in test_write_reports
    self._call()
  File "tests/integration/test_unkillable_shutdown.py", line 57, in _call
    self.assertEqual(process.returncode, 0, process.stderr)
AssertionError: 1 != 0 : WARNING: ignoring: 1
ERROR: Cannot create report: [Errno 17] File exists: '/tmp/tmpmanp_qtj/_usr_sbin_dnsmasq.0.crash'
```

Instead of failing, print a warning instead.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>