problem_report: assert correct value type in _write_ascii_item
mypy will complain if `ProblemReport` will get type hints:

```
error: Argument 1 to "len" has incompatible type "CompressedFile | CompressedValue | tuple[Any, ...]"; expected "Sized"  [arg-type]
error: Value of type "CompressedFile | CompressedValue | tuple[Any, ...]" is not indexable  [index]
```

`ProblemReport._write_ascii_item` is only called on ASCII keys. Those
keys cannot have values of type `CompressedFile` or `CompressedValue`
according to `_get_sorted_keys`.

So add a `isinstance` assertion to make mypy happy.