test: fix C warning about implicit int
gcc will complain:

```
crash.c: In function ‘f’:
crash.c:2:5: error: type of ‘x’ defaults to ‘int’ [-Wimplicit-int]
    2 | int f(x) {
      |     ^
```

This is equivalent to commit a730657a2f8d
("test/test_report.py: Fix C warnings").