apport-gtk: Gracefully handle import failure of gi
apport-gtk can fail to start during an upgrade from Ubuntu 20.04 (focal)
to Ubuntu 22.04 (jammy):

```
Traceback (most recent call last):
  File "/usr/share/apport/apport-gtk", line 19, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```

Print an error message in case importing `gi` fails.

Bug: https://launchpad.net/bugs/1980561
Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>