tests: Do not require specific locale setting
Set the locale for tests that require a specific language so that the
tests will succeed regardless of the `LANGUAGE` environment variable
setting.

The call `locale.setlocale(locale.LC_TIME, '')` can fail with:

```
locale.Error: unsupported locale setting
```

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>