apport-kde: support launching on Wayland
apport-kde refuses to launch on a Kubuntu 24.04 (noble) Wayland session
(where `WAYLAND_DISPLAY` is set):

```
$ env -u DISPLAY ubuntu-bug
ERROR: This program needs a running X session. Please see "man apport-cli" for a command line version of Apport.
```

apport-kde starts succeesful if only `WAYLAND_DISPLAY` is set. So relax
the display server check to the same as apport-gtk.