tests: Skip SegvAnalysis for non x86 architectures
`add_info` from `data/general-hooks/parse_segv.py` only runs for the
architectures `x86` and `x86_64`. Therefore
`test_add_zz_parse_segv_details` will fail on non x86 architectures:

```
FAIL: test_add_zz_parse_segv_details (__main__.T)
parse-segv produces sensible results
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/integration/test_report.py", line 730, in test_add_zz_parse_segv_details
    self.assertIn('not located in a known VMA region', pr['SegvAnalysis'])
AssertionError: 'not located in a known VMA region' not found in 'Skipped: missing required field "ProcMaps"'
```

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>