test: Do not rely on how the test are executed
Running `test_recoverable_problem.py` with unittest instead of calling
the script directly will cause the test to fail:

```
$ python3 -m unittest test/test_recoverable_problem.py
======================================================================
FAIL: test_recoverable_problem (test.test_recoverable_problem.T)
recoverable_problem with valid data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_recoverable_problem.py", line 54, in test_recoverable_problem
    path = self.wait_for_report()
  File "test/test_recoverable_problem.py", line 37, in wait_for_report
    self.assertTrue(seconds < 10, 'timeout while waiting for %s to be created.' % path)
AssertionError: False is not true : timeout while waiting for [...]_python3 -m unittest.1000.crash to be created.

======================================================================
FAIL: test_recoverable_problem_dupe_sig (test.test_recoverable_problem.T)
recoverable_problem duplicate signature includes ExecutablePath
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_recoverable_problem.py", line 65, in test_recoverable_problem_dupe_sig
    path = self.wait_for_report()
  File "test/test_recoverable_problem.py", line 37, in wait_for_report
    self.assertTrue(seconds < 10, 'timeout while waiting for %s to be created.' % path)
AssertionError: False is not true : timeout while waiting for [...]_python3 -m unittest.1000.crash to be created.

----------------------------------------------------------------------
```

The crash file is named
`_usr_lib_python3.10_unittest___init__.py.1000.crash` in that case.

Since the test case creates a temporary directory for the crash file,
just look for the first crash file to appear.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>