test: Fix test_find_package_desktopfile
network-manager-gnome 1.24.0-1ubuntu3 ships three desktop files:

* /etc/xdg/autostart/nm-applet.desktop
* /usr/share/applications/nm-applet.desktop
* /usr/share/applications/nm-connection-editor.desktop

Both `nm-applet.desktop` files have `NoDisplay=true` set. So only
`nm-connection-editor.desktop` is a displayed desktop file and therefore
`find_package_desktopfile` will return `nm-connection-editor.desktop`.

```
======================================================================
FAIL: test_find_package_desktopfile (test.test_fileutils.T)
find_package_desktopfile()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_fileutils.py", line 92, in test_find_package_desktopfile
    self.assertEqual(apport.fileutils.find_package_desktopfile(multidesktop),
AssertionError: '/usr/share/applications/nm-connection-editor.desktop' != None : multi-desktop package network-manager-gnome

----------------------------------------------------------------------
```

Do not count desktop files with `NoDisplay=true` when searching for
packages with more than two desktop files for `multidesktop`.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>