tests: Fix one-desktop package test on apport-kde
The apport-kde package contains two .desktop files:

* /usr/share/applications/apport-kde-mime.desktop
* /usr/share/mimelnk/text/apport-kde-mimelnk.desktop

The first desktop files sets `NoDisplay=true`. The second one is not in
`/usr/share/applications`. Therefore `find_package_desktopfile` returns
`None`, which is the correct and desired result.

The autopkgtest fails for it:

```
FAIL: test_find_package_desktopfile (__main__.T)
find_package_desktopfile()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_fileutils.py", line 103, in test_find_package_desktopfile
    self.assertNotEqual(d, None, 'one-desktop package %s' % onedesktop)
AssertionError: None == None : one-desktop package apport-kde
```

Correct `test_find_package_desktopfile` to skip `/usr/share/mimelnk`
when searching for a package that fits in the `onedesktop` category.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>