tests: Set HOME for apt/dpkg backend tests
Several apt/dpkg backend tests fail during Debian package build, because
sbuild points the home directory to a non-existing path:

```
ERROR: test_install_packages_from_launchpad (__main__.T)
install_packages() using packages only available on Launchpad
----------------------------------------------------------------------
Traceback (most recent call last):
  File "backends/packaging-apt-dpkg.py", line 887, in install_packages
    cache_pkg.candidate = cache_pkg.versions[ver]
  File "/usr/lib/python3/dist-packages/apt/package.py", line 990, in __getitem__
    raise KeyError("Version: %r not found." % (item))
KeyError: "Version: '1.6.6-0ubuntu0.14.04.1' not found."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/test_backend_apt_dpkg.py", line 841, in test_install_packages_from_launchpad
    obsolete = impl.install_packages(self.rootdir, self.configdir, 'Foonux 14.04',
  File "backends/packaging-apt-dpkg.py", line 889, in install_packages
    (lp_url, sha1sum) = self.get_lp_binary_package(self.get_distro_name(),
  File "backends/packaging-apt-dpkg.py", line 261, in get_lp_binary_package
    launchpad = Launchpad.login_anonymously('apport-retrace', 'production',
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 491, in login_anonymously
    ) = cls._get_paths(service_root, launchpadlib_dir)
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 789, in _get_paths
    os.makedirs(launchpadlib_dir, 0o700)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/sbuild-nonexistent'
```

So set the `HOME` environment variable to a temporary directory during
the apt/dpkg backend tests to allow the Launchpad library to create
`~/.launchpadlib`.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>