Fix calling in_session_of_problem with a dict
Since commit 9959a0addf76 ("Replace ProblemReport.get_date by
.get_timestamp"), `in_session_of_problem` requires a `Report` object and
not a `dict`. Otherwise it will fail:

```
ERROR: test_in_session_of_problem (tests.integration.test_hookutils.T)
in_session_of_problem()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/integration/test_hookutils.py", line 407, in test_in_session_of_problem
    self.assertFalse(apport.hookutils.in_session_of_problem(report))
  File "apport/hookutils.py", line 1139, in in_session_of_problem
    report_time = report.get_timestamp()
AttributeError: 'dict' object has no attribute 'get_timestamp'
```

Do not fail if a `dict` is passed to `in_session_of_problem` and replace
`dict` by `Report` in `test_in_session_of_problem` (except for one case
to test that `in_session_of_problem` can handle an empty dictionary).

Bug: https://launchpad.net/bugs/1978487
Fixes: 9959a0addf76 ("Replace ProblemReport.get_date by .get_timestamp")
Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>