apport-cli: Fix AttributeError: 'bytes' object has no attribute 'fileno'
apport-cli fails when viewing the crash report:

```
Traceback (most recent call last):
  File "bin/apport-cli", line 187, in ui_update_view
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 835, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python3.10/subprocess.py", line 1606, in _get_handles
    p2cread = stdin.fileno()
AttributeError: 'bytes' object has no attribute 'fileno'
```

The `stdin` parameter for `subprocess.run` must be an existing file
descriptor or an existing file object with a valid file descriptor. Use
the `input` for byte sequences.

Bug: https://launchpad.net/bugs/1991200
Fixes: 9340a43dd934 ("Use subprocess.run instead of subprocess.Popen")
Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>