tests: fix mypy 1.9.0 complains
mypy 1.9.0 complains:

```
tests/integration/test_problem_report.py:539: error: Argument 1 to "write" of "BufferedWriter" has incompatible type "Message | bytes | Any"; expected "Buffer"  [arg-type]
tests/integration/test_crashdb_launchpad.py:759: error: Item "Message" of "Message | bytes | Any" has no attribute "decode"  [union-attr]
Found 2 errors in 2 files (checked 85 source files)
```

The changes to `tests/integration/test_problem_report.py` were tested on
my machine:

```
TEST_LAUNCHPAD=1 pytest tests/integration/test_crashdb_launchpad.py
```