test: delete variables instead of assigning None
mypy complains:

```
tests/system/test_signal_crashes.py:150: error: Incompatible types in assignment (expression has type "None", variable has type "Report")  [assignment]
tests/system/test_signal_crashes.py:189: error: Incompatible types in assignment (expression has type "None", variable has type "bytes")  [assignment]
```

Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>