apport-gtk: Fix importing the wrong Gdk version
apport-gtk from Apport 2.22.0 fails:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 142, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 257, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 109, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/apport/apport-gtk", line 28, in <module>
    from gi.repository import Gdk, GdkX11, GLib, Gtk, Wnck
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 144, in load_module
    raise ImportError(e)
ImportError: Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded
```

Explicitly specify the required Gdk and Gtk versions.

Fixes: ed19a75992b7 ("Sort Python imports with isort")
Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>