apt_dpkg: fix GDB command for amd64 sandbox on non-amd64
`test_retrace_jammy_sandbox` fails on non-amd64 (e.g. on arm64):

```
$ pytest tests/system/test_apport_retrace.py::test_retrace_jammy_sandbox
[...]
/usr/lib/python3.14/subprocess.py:578: CalledProcessError
--------------------------- Captured stdout call ---------------------------
Get:1 http://de.archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://de.archive.ubuntu.com/ubuntu jammy/main Sources [1340 kB]
Get:3 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1395 kB]
Get:4 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 Components [423 kB]
Get:5 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 c-n-f Metadata [30.3 kB]
Fetched 3458 kB in 0s (0 B/s)
Fetched 0 B in 0s (0 B/s)
Extracting downloaded debs...
dynamically loaded /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 needs package libc6, queueing
dynamically loaded /usr/lib/x86_64-linux-gnu/libc.so.6 needs package libc6, queueing
Installing extra package coreutils to get ExecutablePath
Get:1 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 libc6 amd64 2.35-0ubuntu3 [3235 kB]
Get:2 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 coreutils amd64 8.32-4.1ubuntu1 [1438 kB]
Get:3 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 libc6-dbg amd64 2.35-0ubuntu3 [13.9 MB]
Get:4 [6087 kB]
Fetched 24.7 MB in 0s (0 B/s)
Extracting downloaded debs...
--------------------------- Captured stderr call ---------------------------
ERROR: [Errno 2] No such file or directory: '/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2'
```

Avoid calling binaries from other architectures to determine the library
search path. So add a hard-coded mapping from the Debian architecture to
the multi-arch triplet instead.

Extent `get_library_paths` to take an optional `architecture` parameter
which returns the default value from ld.so.

The dpkg-dev dependency can be dropped for the integration tests,
because `dpkg-architecture` is not called any more.

Bug: https://launchpad.net/bugs/2150427
(cherry picked from commit e1915e540c759cbb23cb2ab19fbb8f79a0d2b8fb)