tests: Determine source package dynamically in test_run_crash_kernel
The autopkgtest for apport 2.23.1-0ubuntu1 fails on ppc64el:

```
======================================================================
FAIL: test_run_crash_kernel (tests.integration.test_ui.T)
run_crash() for a kernel error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "tests/integration/test_ui.py", line 1617, in test_run_crash_kernel
    self.assertEqual(
AssertionError: 'http://linux.bugs.example.com/5' != 'http://linux-signed.bugs.example.com/5'
- http://linux.bugs.example.com/5
+ http://linux-signed.bugs.example.com/5
? +++++++

----------------------------------------------------------------------
```

Sometimes the Linux source package is `linux` and sometimes
`linux-signed`. Instead of hard-coding the source package name,
determine it dynamically on the running system.

Bug: https://launchpad.net/bugs/1992172
Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>