Set HOME to /nonexistent when calling gdb
The test case `test_add_gdb_info_exe_missing` will fail on Ubuntu 22.04
with non English locale configured:

```
$ python3 -m unittest test.test_report.T.test_add_gdb_info_exe_missing
Warnung: Memory read failed for corefile section, 4096 bytes at 0xffffffffff600000.
WARNING: Please install gdb-multiarch for processing reports from foreign architectures. Results with "gdb" will be very poor.
WARNING: Please install gdb-multiarch for processing reports from foreign architectures. Results with "gdb" will be very poor.
F
======================================================================
FAIL: test_add_gdb_info_exe_missing (test.test_report.T)
add_gdb_info() with missing executable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_report.py", line 693, in test_add_gdb_info_exe_missing
    self.assertRaises(FileNotFoundError, pr.add_gdb_info)
AssertionError: FileNotFoundError not raised by add_gdb_info

----------------------------------------------------------------------
Ran 1 test in 0.546s

FAILED (failures=1)
```

Printing the output of the `gdb` call shows that some error messages
from gdb are translated (even with no environment variable set).

Setting an environment variable (like `LC_ALL=C`) when calling gdb will
trigger a warning:

```
/usr/bin/gdb: warning: Couldn't determine a path for the index cache directory.
```

So set the environment variable `HOME` to `/nonexistent` to prevent this
warning and to cause gdb to use C locale.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>