crashdb: add type hints
Add type hints to apport.crashdb except for functions/methods that
involve `Report` since that would lead to cyclic imports:

```
Traceback:
apport/__init__.py:8: in <module>
    from apport.report import Report
apport/report.py:50: in <module>
    from apport.ui import HookUI, NoninteractiveHookUI
apport/ui.py:49: in <module>
    import apport.crashdb
apport/crashdb.py:27: in <module>
    from apport.report import Report
E   ImportError: cannot import name 'Report' from partially initialized module 'apport.report' (most likely due to a circular import) (apport/report.py)
```