java_uncaught_exception: Avoid unused variables
Do not unpack the result of `urlparse`, because only `scheme` and `path`
are needed.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>