test: Skip Java tests if class/jar files are missing
If the class/jar files are not built, the Java test cases will fail:

```
======================================================================
FAIL: test_crash_class (__main__.T)
Crash in a .class file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_java_crashes.py", line 45, in test_crash_class
    self.assertTrue(b"Can't catch this" in err,
AssertionError: False is not true : crash handler must print original exception:
Error: Could not find or load main class crash
Caused by: java.lang.ClassNotFoundException: crash

======================================================================
FAIL: test_crash_jar (__main__.T)
Crash in a .jar file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_java_crashes.py", line 58, in test_crash_jar
    self.assertTrue(b"Can't catch this" in err,
AssertionError: False is not true : crash handler must print original exception:
Error: Could not find or load main class crash
Caused by: java.lang.ClassNotFoundException: crash

----------------------------------------------------------------------
```

Check for the presence of the needed class/jar files and skip the test
cases if they are missing. To build the class/jar files, run:

```
./setup.py build_java_subdir
```

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>