test: use tempfile.TemporaryDirectory in test_add_proc_info
mypy complains:

```
tests/integration/test_report.py:239: error: Incompatible types in assignment (expression has type "int", variable has type "TextIOWrapper[_WrappedBuffer]")  [assignment]
tests/integration/test_report.py:241: error: Argument 1 to "write" has incompatible type "TextIOWrapper[_WrappedBuffer]"; expected "int"  [arg-type]
tests/integration/test_report.py:250: error: Argument 1 to "close" has incompatible type "TextIOWrapper[_WrappedBuffer]"; expected "int"  [arg-type]
```

So use `tempfile.TemporaryDirectory` in `test_add_proc_info`. Using
`tempfile.NamedTemporaryFile(delete_on_close=False)` would be better,
but the `delete_on_close` parameter requires Python >= 3.12.