test: ensure orig_apt_proxy is always a string
mypy complains:

```
tests/system/test_packaging_apt_dpkg.py:490: error: Argument 2 to "set" of "Configuration" has incompatible type "str | None"; expected "str"  [arg-type]
```

`apt_pkg.config.get` will return an empty string in case the config is
not set. So it is safe to let the `get` method return an empty string as
fallback value.

Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>