report: assert that the CoreDump field is not a string
According to the documentation (see doc/data-format.tex) the `CoreDump`
field in the report must have a binary value. Constructing a report with
a text value crashes (tested with Apport 2.31.0-0ubuntu5):

```
$ apport-retrace _usr_bin_divide-by-zero.1000.crash
Traceback (most recent call last):
  File "/usr/bin/apport-retrace", line 701, in <module>
    sys.exit(main(sys.argv[1:]))
             ~~~~^^^^^^^^^^^^^^
  File "/usr/bin/apport-retrace", line 576, in main
    report.add_gdb_info(sandbox, gdb_sandbox)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apport/report.py", line 958, in add_gdb_info
    gdb_cmd, environ = self.gdb_command(rootdir, gdb_sandbox)
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1935, in gdb_command
    os.write(fd, self["CoreDump"])
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

So assert that `CoreDump` is not a str.