fix: Catch binascii.Error: Incorrect padding
The problem report might be malformed which lets `whoopsie-upload-all`
crash:

```
Traceback (most recent call last):
  File "data/whoopsie-upload-all", line 250, in <module>
    main()
  File "data/whoopsie-upload-all", line 232, in main
    stamps = collect_info()
  File "data/whoopsie-upload-all", line 163, in collect_info
    res = process_report(r)
  File "data/whoopsie-upload-all", line 77, in process_report
    r.load(f, binary="compressed")
  File "problem_report.py", line 147, in load
    bd, value = self._decompress_line(line, bd, value)
  File "problem_report.py", line 296, in _decompress_line
    block = base64.b64decode(line)
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

Catch the `binascii.Error` and raise a `MalformedProblemReport`
exception instead (which is catched by `whoopsie-upload-all` and
`apport-unpack`).

Bug: https://launchpad.net/bugs/1997912
Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>