fix(apport-kde): Add notr parameter to translate function
mypy complains:

```
kde/apport-kde:74: error: Incompatible types in assignment (expression has type "Callable[[Any, Any], Any]", variable has type "Callable[[Properties, Any, Any], Any]")  [assignment]
```

`PyQt5.uic.properties.Properties._string` has the additional parameter
`notr` since at least PyQt 5.10.1 (tested on Ubuntu 18.04 "bionic"). The
`_string` method has not been changed since then (tested PyQt5 5.15.9 on
Ubuntu 23.04 "lunar").

Add `notr` parameter to the `translate` function and make the code more
similar to the upstream code.

Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>