Fix AttributeError: module 'importlib' has no attribute 'util'
On Ubuntu 22.10 (kinetic) some test cases fail during package build
with:

```
Traceback (most recent call last):
  File "data/recoverable_problem", line 84, in <module>
    main()
  File "data/recoverable_problem", line 44, in main
    report.add_proc_info(report.pid)
  File "apport/report.py", line 701, in add_proc_info
    self._check_interpreted()
  File "apport/report.py", line 541, in _check_interpreted
    path = self._python_module_path(cmdargs[2])
  File "report.py", line 618, in _python_module_path
    spec = importlib.util.find_spec(module)
AttributeError: module 'importlib' has no attribute 'util'
```

Bug: https://launchpad.net/bugs/1947425
Fixes: 44d1c43231d7 ("Replace deprecated 'imp' module")
Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>