apt_dpkg: Skip parsing non-deb files with dpkg-deb
The test case `TestApportValgrind.test_sandbox_cache_options` started to
fail on the system-tests-installed CI run:

```
dpkg-deb: error: '/tmp/tmp4wlfuaxh/test-cache/system/apt/var/lib/apt/lists/auxfiles/_etc_apt_apt-mirrors.txt' is not a Debian format archive
Traceback (most recent call last):
  File "/usr/bin/apport-valgrind", line 159, in <module>
    sandbox, cache, outdated_msg = apport.sandboxutils.make_sandbox(
  File "/usr/lib/python3/dist-packages/apport/sandboxutils.py", line 226, in make_sandbox
    outdated_msg = packaging.install_packages(
  File "/usr/lib/python3/dist-packages/apport/packaging_impl/apt_dpkg.py", line 1302, in install_packages
    out = subprocess.check_output(["dpkg-deb", "--show", i.destfile]).decode()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '--show', '/tmp/tmp4wlfuaxh/test-cache/system/apt/var/lib/apt/lists/auxfiles/_etc_apt_apt-mirrors.txt']' returned non-zero exit status 2.
```

Judging from the file name `_etc_apt_apt-mirrors.txt`, this file is not
a Debian package. Therefore skip files not ending with `deb` (`ddeb` and
`udeb` will be covered).

Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>