tests: Mock kernel package version in UI test
The kernel package might not be installed in the test environment (e.g.
in a schroot or Docker container). Then
`test_run_report_bug_kernel_thread` will fail:

```
ERROR: test_run_report_bug_kernel_thread (tests.test_ui.T)
run_report_bug() for a pid of a kernel thread
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ui.py", line 706, in test_run_report_bug_kernel_thread
    self.ui.run_argv()
  File "apport/ui.py", line 697, in run_argv
    return self.run_report_bug()
  File "apport/ui.py", line 495, in run_report_bug
    self.collect_info(symptom_script)
  File "apport/ui.py", line 1256, in collect_info
    sys.exit(1)
SystemExit: 1
```

Therefore mock `get_version` for the kernel package. All other calls for
`get_version` will return the same mocked version, but
`test_run_report_bug_kernel_thread` does not care about this detail.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>