test: Mock ~/.apport-ignore.xml path
Running `test.test_python_crashes.T.test_ignoring` during Debian package
build fails, because the home directory does not exist:

```
======================================================================
ERROR: test_ignoring (__main__.T)
the Python crash hook respects the ignore list.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_python_crashes.py", line 271, in test_ignoring
    r.mark_ignore()
  File "apport/report.py", line 1190, in mark_ignore
    with open(ignore_file_path, 'w') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.apport-ignore.xml'
```

To be able to run the test without an existing home directory, mock the
`.apport-ignore.xml` file.

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>