whoopsie-upload-all: Fix 'EOFError' object has no attribute 'errno'
```
Traceback (most recent call last):
  File "data/whoopsie-upload-all", line 106, in process_report
    r.add_gdb_info()
  File "apport/report.py", line 883, in add_gdb_info
    gdb_cmd, environ = self.gdb_command(rootdir, gdb_sandbox)
  File "apport/report.py", line 1935, in gdb_command
    self["CoreDump"].write(f)
  File "problem_report.py", line 75, in write
    block = gz.read(1048576)
  File "/usr/lib/python3.10/gzip.py", line 301, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.10/gzip.py", line 507, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data/whoopsie-upload-all", line 248, in <module>
    main()
  File "data/whoopsie-upload-all", line 230, in main
    stamps = collect_info()
  File "data/whoopsie-upload-all", line 161, in collect_info
    res = process_report(r)
  File "data/whoopsie-upload-all", line 131, in process_report
    if getattr(e, "errno") != errno.ENOENT:
AttributeError: 'EOFError' object has no attribute 'errno'
```

Bug: https://launchpad.net/bugs/1979681
Fixes: 655cea618502 ("whoopsie-upload-all: Do not upload after EOFError/zlib.error")
Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>